//
//  CardPresenter.swift
//  TestProject
//
//  Created by Roman Kiruxin on 19.10.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardPresentationLogic {
    func presentSomething(response: Card.Something.Response)
}

class CardPresenter: CardPresentationLogic {
    
    weak var viewController: CardDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Card.Something.Response) {
        let viewModel = Card.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
