//
//  TabBarViewController.swift
//  TestProject
//
//  Created by Roman Kiruxin on 19.10.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabBarDisplayLogic: AnyObject {
  
}

final class TabBarViewController: UITabBarController {
    
    // MARK: - IBOutlets
    
    
    // MARK: - External vars
    var interactor: TabBarBusinessLogic?
    var router: (NSObjectProtocol & TabBarRoutingLogic & TabBarDataPassing)?

  // MARK: - Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        TabBarConfigurator.shared.configure(self)
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        TabBarConfigurator.shared.configure(self)
    }
  
    // MARK: - View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    // MARK: - IBActions
    
}

// MARK: - Display logic
extension TabBarViewController: TabBarDisplayLogic {
    
}

// MARK: - Private methods
private extension TabBarViewController {
    
    func setupView() {
        setupTabBar()
        setupViewControllers()
    }
    
    func setupTabBar() {
        tabBar.tintColor = R.color.tabBarTintColor()
        tabBar.backgroundColor = R.color.tabBarBackground()
        
        UITabBarItem.appearance().setTitleTextAttributes([NSAttributedString.Key.font: R.font.sfuiDisplayLight(size: 13) ?? UIFont.systemFont(ofSize: 13, weight: .regular)],
                                                         for: .normal)
        UITabBarItem.appearance().setTitleTextAttributes([NSAttributedString.Key.font: R.font.sfuiDisplayLight(size: 13) ?? UIFont.systemFont(ofSize: 13, weight: .regular)],
                                                         for: .selected)
    }
    
    func setupViewControllers() {
        let catalog = CatalogViewController()
        let card = CardViewController()
        let profile = ProfileViewController()
        let contacts = ContactsViewController()
        
        catalog.tabBarItem.image = R.image.tabMenu()
        card.tabBarItem.image = R.image.tabCart()
        profile.tabBarItem.image = R.image.tabProfile()
        contacts.tabBarItem.image = R.image.tabContacts()
        
        catalog.tabBarItem.title = "Меню"
        card.tabBarItem.title = "Корзина"
        profile.tabBarItem.title = "Профиль"
        contacts.tabBarItem.title = "Контакты"
        
        setViewControllers([catalog, contacts, profile, card], animated: false)
    }
}

