//
//  ContactsPresenter.swift
//  TestProject
//
//  Created by Roman Kiruxin on 19.10.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactsPresentationLogic {
    func presentSomething(response: Contacts.Something.Response)
}

class ContactsPresenter: ContactsPresentationLogic {
    
    weak var viewController: ContactsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Contacts.Something.Response) {
        let viewModel = Contacts.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
